apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: deo
  name: deo-frontend-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deo-frontend
  template:
    metadata:
      labels:
        app: deo-frontend
    spec:
#      imagePullSecrets:
#      - name: ghcr-login-secret
      containers:
      - name: deo-frontend
        image: ghcr.io/stadler-pascal/deo-webapp-frontend:v1.1
        args: ["--urls", "http://*:4000"]
        ports:
        - containerPort: 4000
        env:
        - name: DEO_BACKEND_URL
          value: "http://deo-backend-svc:5000"
