apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: deo
  name: deo-backend-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deo-backend
  template:
    metadata:
      labels:
        app: deo-backend
    spec:
#      imagePullSecrets:
#      - name: ghcr-login-secret
      containers:
      - name: deo-backend
        image: ghcr.io/jkarder/deo-webapp-backend:latest
        args: ["--urls", "http://*:5000"]
        ports:
        - containerPort: 5000
