apiVersion: v1
kind: Service
metadata:
  namespace: deo
  name: deo-frontend-svc
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 2000
      targetPort: 2000
  selector:
    app: deo-frontend
