apiVersion: v1
kind: Service
metadata:
  namespace: deo
  name: deo-backend-svc
spec:
  clusterIP: None
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: deo-backend
