name: Package Pipeline

run-name: Packaging triggered by ${{ github.actor }} 📦

on:
    push:
        tags:
            - v*

env:
    REGISTRY: ghcr.io
    BACKEND_IMAGE_NAME: ${{ github.repository }}-backend 
    FRONTEND_IMAGE_NAME: ${{ github.repository }}-frontend


jobs: 
    build-and-push-backend-image:
        runs-on: ubuntu-latest
        permissions: 
            contents: read
            packages: write
#            id-token: write
#            attestations: write
        steps:
          - name: Check out repository code
            uses: actions/checkout@v4
          - name: Login to container registry
            uses: docker/login-action@v3
            with:
                registry: ${{ env.REGISTRY }}
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
          - name: Extract metadata
            id: meta
            uses: docker/metadata-action@v5
            with:
                images: ${{ env.REGISTRY}}/${{ env.BACKEND_IMAGE_NAME }}                
          - name: Build and push image
            id: push
            uses: docker/build-push-action@v6
            with:
                context: ./Deo.Backend
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
#          - name: Generate artifact attestation
#            uses: actions/attest-build-provenance@v1
#            with:
#              subject-name: ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}
#              subject-digest: ${{ steps.push.outputs.digest }}
#              push-to-registry: true
    build-and-push-frontend-image:
        runs-on: ubuntu-latest
        permissions: 
            contents: read
            packages: write
#            id-token: write
#            attestations: write
        steps:
          - name: Check out repository code
            uses: actions/checkout@v4
          - name: Login to container registry
            uses: docker/login-action@v3
            with:
                registry: ${{ env.REGISTRY }}
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
          - name: Extract metadata
            id: meta
            uses: docker/metadata-action@v5
            with:
                images: ${{ env.REGISTRY}}/${{ env.FRONTEND_IMAGE_NAME }}                
          - name: Build and push image
            id: push
            uses: docker/build-push-action@v6
            with:
                context: ./Deo.Frontend
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
#          - name: Generate artifact attestation
#            uses: actions/attest-build-provenance@v1
#            with:
#                subject-name: ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}
#                subject-digest: ${{ steps.push.outputs.digest }}
#                push-to-registry: true
            
